# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# https://copier.readthedocs.io/en/stable/updating/#never-change-the-answers-file-manually
_commit: v2.0.0
_src_path: gh:FallingColors/hexdummy
advanced: false
description: Hex Shadow Items addon for Hex Casting
display_name: Hex Shadow Items
github_repo: HexShadowItems
github_user: Wolverine-14
mappings_name: Mojmap
minecraft_version_in_mod_version: false
mod_version: 0.0.1
modid: shadowitems
package: io.github.wolverine14.hexshadowitems
